// "use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Navbar";
import WrapNextUI from "./components/WrapNextUI";
import Sidebar from "./components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blackdit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <WrapNextUI>
        <body className={inter.className}>
          <div>
            <Nav />
            <div className="flex flex-row min-h-screen">
              <Sidebar />
              {children}
            </div>
          </div>
        </body>
      </WrapNextUI>
    </html>
  );
}
